### ISSUE TITLE
Add DB setup in setup script

### ISSUE THREAD

**Issue by nisargjhaveri** [nisargjhaveri/saathi#2]

**Comment by gauravmittal1995** [comment]
@ParthKolekar @nisargjhaveri Is this issue done? If yes, Please close it.

**Comment by ParthKolekar** [comment]
@gauravmittal1995 
I am leaving this task open. 
Please look into it. 

Task is rather simple, the _install of the script should contain a mysql add command using your corrected .sql file.

**Comment by ParthKolekar** [comment]
Marked for Close.

**Comment by gauravmittal1995** [comment]
I am not working on this. Whoever did the setup.sh complete this as well.

**Comment by ParthKolekar** [comment]
@gauravmittal1995 Then I will finish the setup.

**Comment by gauravmittal1995** [comment]
@ParthKolekar :+1:  Thanks. But i think its better to wait before https://github.com/nisargjhaveri/saathi/pull/12 gets merged.

**Comment by gauravmittal1995** [comment]
will simply break the script otherwise

**Comment by nisargjhaveri** [comment]
I think we don't need this anymore, as not many people are complaining about this. Closing for now.

**Comment by gauravmittal1995** [comment]
This will be useful once we start with prepopulation. So for now we can close it.
