### ISSUE TITLE
ER Issues

### ISSUE THREAD

**Issue by chandan5** [nisargjhaveri/saathi#6]
![10498572_10153127203649454_54200328522409945_o](https://cloud.githubusercontent.com/assets/9067276/6863498/d415ea7a-d478-11e4-8e63-b8de1321f486.jpg)
1. "assets" has organisation_id -> Of what use? -> We made "requests" to deal with it.
2. Is "assets" used for donation then where is count?

If anybody has any other issues related to ER mention here.

**Comment by gauravmittal1995** [comment]
@imjalpreet ^

**Comment by ParthKolekar** [comment]
Assign to someone @nisargjhaveri

**Comment by nisargjhaveri** [comment]
I think it would be better if one who is working on some module, update it as required.

**Comment by chandan5** [comment]
Ok I will update it..

**Comment by nisargjhaveri** [comment]
Agreed, there are still many problems with this. But thinking everything at once and conveying the design in someone's mind to everyone is bit tough.

**Comment by ParthKolekar** [comment]
I for one, do not think that the asset deserves to be directly linked to an org.
Comments?

**Comment by nisargjhaveri** [comment]
Agreed.

To add, even supplier and date is not needed in asset. These things should be handles in request.

**Comment by ParthKolekar** [comment]
supplier is needed. 

Supplier reference to org, rather than to contact_details

**Comment by gauravmittal1995** [comment]
No, we need a contact detail, and supplier is not neccessarly an org. It can be an individual also

**Comment by gauravmittal1995** [comment]
So supplier is for contact_details, not an org.

**Comment by gauravmittal1995** [comment]
and supplier is needed, coz the requestee doesnt care where the asset comes form, if its available , it takes it

**Comment by ParthKolekar** [comment]
I do not agree with mine nor you approach to things, @gauravmittal1995 .
But yours will make more sense.

**Comment by souravsarangi** [comment]
Its getting difficult to find actual persons related to an organization. They dont provide those details. Can we use their local/regional phone no.s/email  instead?

**Comment by nisargjhaveri** [comment]
Also see #19.

**Comment by nisargjhaveri** [comment]
I think, this is now outdated.

If you have any new issue related ER, please create new issues.
